from .main import main
from .user import user
from .notes import notes
from .professional_development import professional_development
from .folder import folders_bp 
from .file import files_bp
from .links import links_bp
from .schedule import schedule_bp
from .course import course_bp 
from .questions import questions_bp
from .userCourse import userCourse_bp
from .attendanceLog import attendanceLog_bp
from .assistent import assistent_bp
